### ISSUE TITLE
Featured News and other content block hover issues

### ISSUE THREAD

**Issue by bdrutl** [redacademy/montessori-summer-2016#12]
Below applies to the featured news blocks on the homepage, and similar blocks used in at least one other place in the site.

Make sure the cursor is set to pointer when hovering over the featured news items to indicate 'click' to the user.

Fix the hover issue. When I hover over the blocks, the hover state is not fully triggered if my cursor is not in the center.

'Read More'  needs to be added for hover.

Make sure the content is aligned properly on hover.

Use URL parameter in featured news links on homepage to pull up the correct, relevant content on the next page when clicked.

**Comment by ayahalhasan** [comment]
all done!!!
